### ISSUE TITLE
Can't add a provider with self-hosted box URL

### ISSUE THREAD

**Issue by legal90** [nickcharlton/atlas-ruby#1]
@nickcharlton Thank you for this useful library!

May be, I do it wrong, but I can't add a provider with pre-defined download URL:

``` ruby
provider = version.create_provider(name: 'parallels', url: 'http://example.com/path')
```

``` ruby
provider = version.create_provider(name: 'parallels', download_url: 'http://example.com/path')
```

``` ruby
provider = version.create_provider(name: 'parallels')
provider.download_url = 'http://example.com/path'
provider.save
```

None of these 3 ways gives me an expected result. Instead, the provider is marked as "Hosted", with an empty url.

Could you please give me an advice - how should I do that?

**Comment by nickcharlton** [comment]
I think it's possible I didn't implement that, so the behaviour will be undefined.

I'll have a look at this and get back to you. It'll probably need a little bit of adjustment.

**Comment by nickcharlton** [comment]
Hm, so having a look at this again, it looks to me like the first example you gave should work:

``` ruby
provider = version.create_provider(name: 'parallels', url: 'http://example.com/path')
```

But, it's not passing that along directly when it hits `save` (hence it always assumes it's a hosted box).

I'm going to have to give this one some thought (there's also no tests on the file handling, so that's something I need to do also).
