### ISSUE TITLE
Progress bar issues

### ISSUE THREAD

**Issue by genebean** [nickcharlton/atlas-ruby#8]
According to PR #7 I should be able to get a progress bar to work while uploading but for some reason the code below just creates the bar at the beginning of an upload and then jumps to done when the upload finishes. I'm thinking that this is a bug as I all but copied the example code from #7.

```ruby
  if File.exist?(boxpath)
    file = File.open(boxpath)
    progress_bar = ProgressBar.create(total: file.size)

    provider.upload(file) do |progress, size|
      diff = size - progress
      progress_bar.progress += diff if diff < size
    end

    progress_bar.finish
  else
    raise("Unable to fine #{boxpath}")
  end
```

Just in case it helps, this section of code can be seen in context at https://github.com/genebean/boxpusher

**Comment by nickcharlton** [comment]
Hi @genebean,

Unfortunately, I was mistaken when I implemented it originally and you can't do chunked uploads with Atlas. I reverted that in the most recent release ([30dfb26](https://github.com/nickcharlton/atlas-ruby/commit/30dfb26fb2d5064923f83facae93bdc9e0371196)).

You're seeing it complete to the end because it no longer gets that callback until done.

**Comment by genebean** [comment]
Sad... thanks.
